[versions]
kotlin = "2.3.10"
spockk = "0.2.0"

[libraries]
spock-core = { module = "org.spockframework:spock-core", version = "2.4-groovy-5.0" }
spockk-core = { module = "io.github.pshevche.spockk:spockk-core", version.ref = "spockk" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "6.0.2" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-power-assert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
spockk = { id = "io.github.pshevche.spockk", version.ref = "spockk" }
